export-destination: minio://172.17.0.3:9000/doccache-dgraph-backups
export-use-ssl: false
export-access-key: miniouser
export-secret-key: miniopassword
prometheus-port: 2114
export-jobs: 
- name: dho
  gql-admin-url: http://localhost:8080/admin
  schedule: "42 * * * *"
- name: dho2
  gql-admin-url: http://localhost:8080/admin
  schedule: "43,44 * * * *"
