export-destination: minio://172.17.0.3:9000/doccache-dgraph-backups
export-use-ssl: false
export-access-key: miniouser
export-secret-key: miniopassword
export-jobs: 
- name: dho
  gql-admin-url: http://localhost:8080/admin
  schedule: 0 0 0 * * *